In [1]:
import numpy as np

In [2]:
data = np.array([1.3,2,3.6,-4,5.9])
print(data)

[ 1.3  2.   3.6 -4.   5.9]


### mathematical functions

In [3]:
np.sum(data)

np.float64(8.8)

In [4]:
np.mean(data)

np.float64(1.7600000000000002)

In [5]:
np.median(data)

np.float64(2.0)

#### np.mode(data) : not built in so import from statisctics module

In [6]:
np.std(data)

np.float64(3.285483221689011)

In [7]:
np.var(data)

np.float64(10.794400000000001)

In [8]:
np.min(data)

np.float64(-4.0)

In [9]:
np.max(data)

np.float64(5.9)

In [25]:
np.sqrt(data)

C:\Users\hp\AppData\Local\Temp\ipykernel_4812\1624513065.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(data)


array([1.14017543, 1.41421356, 1.8973666 ,        nan, 2.42899156])

In [11]:
np.square(data)

array([ 1.69,  4.  , 12.96, 16.  , 34.81])

In [12]:
np.round(data)

array([ 1.,  2.,  4., -4.,  6.])

In [13]:
np.ceil(data)

array([ 2.,  2.,  4., -4.,  6.])

In [14]:
np.floor(data)

array([ 1.,  2.,  3., -4.,  5.])

In [15]:
np.exp(data)

array([3.66929667e+00, 7.38905610e+00, 3.65982344e+01, 1.83156389e-02,
       3.65037468e+02])

In [16]:
np.log(data)

C:\Users\hp\AppData\Local\Temp\ipykernel_4812\182692439.py:1: RuntimeWarning: invalid value encountered in log
  np.log(data)


array([0.26236426, 0.69314718, 1.28093385,        nan, 1.77495235])

In [17]:
np.sin(data)

array([ 0.96355819,  0.90929743, -0.44252044,  0.7568025 , -0.37387666])

In [18]:
np.cos(data)

array([ 0.26749883, -0.41614684, -0.89675842, -0.65364362,  0.92747843])

In [19]:
np.tan(data)

array([ 3.60210245, -2.18503986,  0.49346673, -1.15782128, -0.4031109 ])

In [20]:
np.abs(data)

array([1.3, 2. , 3.6, 4. , 5.9])

In [22]:
# data2 = np.array([-2,-5,-7,5])
# np.abs(data2)

array([2, 5, 7, 5])

## Array creation functions

In [26]:
data2 = np.array([2,3,4,6,8,9,10])
print(data2)

[ 2  3  4  6  8  9 10]


In [28]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.full((2,3),5) 

array([[5, 5, 5],
       [5, 5, 5]])

In [40]:
np.arange(1,10,3)

array([1, 4, 7])

In [42]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [57]:
np.random.rand(3)

array([0.28813498, 0.24689964, 0.3878116 ])

In [58]:
np.random.randint(1,10,5) 

array([9, 1, 2, 5, 7], dtype=int32)

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Reshaping and changing aaray

In [73]:
array1 = np.array([[1,2], [3,4], [5,6]])
print(array1)

[[1 2]
 [3 4]
 [5 6]]


In [74]:
array1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
array1.transpose()
print(array1.T)

[[1 3 5]
 [2 4 6]]


In [76]:
a1 = np.array([1,2,3]) 
a2 = np.array([4,5,6])
print(np.concatenate([a1,a2]))

[1 2 3 4 5 6]


In [78]:
np.hstack([a1,a2]) 

array([1, 2, 3, 4, 5, 6])

In [79]:
np.vstack([a1,a2])

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
array1.flatten()

array([1, 2, 3, 4, 5, 6])

In [81]:
array.ravel()

array([100, 100, 100, 100,   5,   6])

## Filtering / Boolean indexing

In [84]:
a = np.array([[1,2], [3,4], [5,6]])

In [85]:
a[a>2]

array([3, 4, 5, 6])

In [86]:
a[(a<6) & (a>=1)]

array([1, 2, 3, 4, 5])

In [87]:
a[a%2 == 0]

array([2, 4, 6])

In [88]:
a[a!=3]

array([1, 2, 4, 5, 6])

## Searching and sorting

In [95]:
s = np.array([1,2,3,4,5,6,3,2,7,9,10,11,34,76])
print(s)

[ 1  2  3  4  5  6  3  2  7  9 10 11 34 76]


In [96]:
np.sort(s) 

array([ 1,  2,  2,  3,  3,  4,  5,  6,  7,  9, 10, 11, 34, 76])

In [97]:
np.argsort(s) 

array([ 0,  1,  7,  2,  6,  3,  4,  5,  8,  9, 10, 11, 12, 13])

In [99]:
np.where(s>2)

(array([ 2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13]),)

In [100]:
np.unique(s)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 34, 76])

## Statisctical imp

### percentile

In [102]:
arr = np.array([10,20,30,40])
print(np.percentile(arr,75))

32.5


In [115]:
import numpy as np

arr1 = [1, 2, 3, 4, 5]
arr2 = [2, 4, 2, 8, 14]

print(np.corrcoef(arr1, arr2))

[[1.         0.86824314]
 [0.86824314 1.        ]]


In [116]:
arr.ndim

1

## extra 

In [106]:
np.random.seed(43)

In [110]:
np.random.randn(3) 

array([-0.43921486, -0.34643789,  0.45531966])

In [111]:
np.random.choice(['female', 'male'], 10)

array(['male', 'female', 'female', 'female', 'male', 'female', 'female',
       'female', 'female', 'male'], dtype='<U6')

In [114]:
np.random.uniform(1,20,12)

array([ 6.23561676, 18.03819813,  4.93093606,  8.68369962, 19.87787736,
       14.97881455,  9.45616684, 11.65260022,  8.81385429, 14.81277185,
        8.58474083, 13.73275813])

## ndim : no of dimension

In [125]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([[1,2], [3,4], [5,6], [7,8]])
n3 = np.array([[[1,2,4],[3,4,5], [5,6,4]]])
print(n1)
print(n2)
print(n3)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2 4]
  [3 4 5]
  [5 6 4]]]


In [126]:
n1.ndim

1

In [127]:
n2.ndim

2

In [128]:
n3.ndim

3