In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np

data = np.array([1,2,3,4,5,6,7,8])
print(data) 
print("type array:",type(data))
print("type of array values:",data.dtype)
print("total values in array:", data.size)
print("total rows and columns count:",data.shape) 
print(data.ndim) 

[1 2 3 4 5 6 7 8]
type array: <class 'numpy.ndarray'>
type of array values: int64
total values in array: 8
total rows and columns count: (8,)
1


In [10]:
data1 = np.array([[1,2,3],[4,5,6]])
print(data1) 
print("type array:",type(data1))
print("type of array values:",data1.dtype)
print("total values in array:", data1.size)
print("total rows and columns count:",data1.shape) 
print("dimensional array:",data1.ndim) 

[[1 2 3]
 [4 5 6]]
type array: <class 'numpy.ndarray'>
type of array values: int64
total values in array: 6
total rows and columns count: (2, 3)
dimensional array: 2


In [9]:
data3 = np.array([[[1,2],[4,5],[6,7]]])
print(data3)
print(data3.shape)  

[[[1 2]
  [4 5]
  [6 7]]]
(1, 3, 2)


In [45]:
np.arange(10,21,2)   #(start,end+1,step) 

array([10, 12, 14, 16, 18, 20])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [72]:
np.random.seed(34) # values change hot nahi randomly aahe tech rahtat
np.random.randint(1,21,4)  #(start,end,howmany) any 4 random nos. from range

array([ 2, 11, 10,  5], dtype=int32)

In [16]:
np.random.randn(3,4)   #(rows,columns)

array([[ 0.72792965,  0.91055995,  0.29883275,  1.06637247],
       [-1.46386182, -2.50693462, -0.24063771, -0.76534267],
       [ 1.10991763, -0.24298159, -1.11815575, -0.49231806]])

In [17]:
np.random.rand(2,3) #only for positives

array([[0.46762703, 0.20562827, 0.81871737],
       [0.90935903, 0.76532086, 0.23926483]])

In [18]:
np.random.uniform(1,21,4)  #(start,end,howmany) for decimal any 4 random nos. from range

array([15.9379183 , 20.9400866 , 14.92052265, 12.25246458])

In [73]:
np.random.choice(['female','male'],10) 

array(['male', 'male', 'male', 'female', 'female', 'male', 'female',
       'male', 'male', 'female'], dtype='<U6')

In [9]:
# employee data

eid = np.arange(1,11)
salary = np.random.randint(10000,60000,10)
gender = np.random.choice(['female','male'],10)
department = np.random.choice(['IT','Analyst','Admin','HR'],10)
exp = np.random.randint(0,5,10)
age = np.random.randint(20,40,10)
rating = np.random.uniform(1,5,10)

In [10]:
print("Employee ID:", eid,
      "\nSalary:", salary,
      "\nGender:", gender,
      "\nDepartment:", department,
      "\nExperience:", exp,
      "\nAge:", age,
      "\nRating:", rating)

Employee ID: [ 1  2  3  4  5  6  7  8  9 10] 
Salary: [50777 45817 51540 42151 59744 28320 54916 38747 19125 17615] 
Gender: ['female' 'female' 'female' 'female' 'female' 'male' 'female' 'female'
 'male' 'female'] 
Department: ['Analyst' 'IT' 'Analyst' 'Analyst' 'Admin' 'HR' 'Admin' 'Admin' 'HR'
 'Analyst'] 
Experience: [3 1 1 2 2 3 2 1 0 2] 
Age: [30 23 35 36 22 21 38 21 31 38] 
Rating: [3.05434212 4.93365869 2.7727784  2.15223451 1.5839662  1.45001849
 2.12424788 1.74350304 1.65477237 3.08039561]


# Array Creation functions

In [11]:
import numpy as np

np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [18]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.full((5,4),2) #adding specific value in matrix as 2 in this code

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [20]:
# IDENTITY matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.linspace(1,5,10) # between 1 to 5 decimals

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# mathematical functions

In [25]:
a = np.array([1,2,3,4,5,6])
b = np.array([10,20,30,40,50,60])

In [26]:
np.add(a,b)

array([11, 22, 33, 44, 55, 66])

In [27]:
np.subtract(a,b)

array([ -9, -18, -27, -36, -45, -54])

In [29]:
np.add(a,10)  # add 10 in a 

array([11, 12, 13, 14, 15, 16])

In [30]:
np.multiply(a,b)

array([ 10,  40,  90, 160, 250, 360])

In [32]:
np.divide(a,b)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [33]:
np.sum(a)

np.int64(21)

In [34]:
np.sum(b)

np.int64(210)

In [35]:
np.min(a)

np.int64(1)

In [36]:
np.max(a)

np.int64(6)

In [37]:
np.mean(a)

np.float64(3.5)

In [38]:
np.median(a)

np.float64(3.5)

In [39]:
np.power(a,2)

array([ 1,  4,  9, 16, 25, 36])

In [40]:
np.power(a,3)

array([  1,   8,  27,  64, 125, 216])

In [41]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [42]:
np.std(a)

np.float64(1.707825127659933)

In [43]:
np.var(a)

np.float64(2.9166666666666665)

In [44]:
np.square(a)

array([ 1,  4,  9, 16, 25, 36])

In [46]:
a1 = np.array([12.54,4,63,6.654,7.6543,67.43])
print(a1)

[12.54    4.     63.      6.654   7.6543 67.43  ]


In [48]:
np.round(a1)  #round off

array([13.,  4., 63.,  7.,  8., 67.])

In [50]:
np.round(a1,1) #only 1 value after decimal

array([12.5,  4. , 63. ,  6.7,  7.7, 67.4])

In [51]:
np.ceil(a1)

array([13.,  4., 63.,  7.,  8., 68.])

In [52]:
np.floor(a1)

array([12.,  4., 63.,  6.,  7., 67.])

In [53]:
np.sin(a1)

array([-0.02636756, -0.7568025 ,  0.1673557 ,  0.36237487,  0.98012978,
       -0.99348147])

In [54]:
#example;

salary = np.array([20000,30000,40000,50000])

In [55]:
np.multiply(salary,12) #package

array([240000, 360000, 480000, 600000])

In [57]:
np.multiply(salary,1.1) #salary increment by 10% 

array([22000., 33000., 44000., 55000.])

# Reshaping and changing array

In [64]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a.reshape(9,1) #used for 1D to multidimensional conversion(a array che numbers reshape array madhey as a number ghene)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [68]:
a3 = np.arange(1,11)
a3


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
a3.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Converting multidimensional to 1D

In [71]:
a3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
a3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## concatenate arrays

In [76]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([6,7,8])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


In [78]:
np.vstack([a,b,c]) # vertical matrix(nD)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [81]:
print(np.hstack([a,b])) # horizontal matrix(1D)
print(np.hstack([a,b,c]))

[1 2 3 4 5 6]
[1 2 3 4 5 6 6 7 8]


## Converting (2,3) into (3,2) :- TRANSPOSE

In [90]:
a1 = np.vstack([a,b])
print(a1)
print(a1.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [94]:
print(a1.T)
print(a1.shape) #It shows previous shape
print(a1.T.shape) #updated shape

[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)


In [ ]:
# Filtering / Boolean Indexing

In [123]:
marks3= np.array([34,65,78,34,75,86,6543,-67,45,3456])
marks3

array([  34,   65,   78,   34,   75,   86, 6543,  -67,   45, 3456])

In [124]:
marks3[marks3>=35]

array([  65,   78,   75,   86, 6543,   45, 3456])

In [125]:
marks3[marks3<35]

array([ 34,  34, -67])

In [126]:
marks3[(marks3>=35) & (marks3<50)]

array([45])

In [127]:
marks3[(marks3>100) | (marks3<0)]

array([6543,  -67, 3456])

In [128]:
np.where(marks3>=35,"pass","fail")

array(['fail', 'pass', 'pass', 'fail', 'pass', 'pass', 'pass', 'fail',
       'pass', 'pass'], dtype='<U4')

In [129]:
marks3[5]

np.int64(86)

In [130]:
marks3[5:]

array([  86, 6543,  -67,   45, 3456])

In [131]:
marks[:5]

[array([False,  True,  True,  True, False,  True,  True,  True, False,
         True,  True])]

In [134]:
marks3.sort()
marks3

array([ -67,   34,   34,   45,   65,   75,   78,   86, 3456, 6543])

In [135]:
a = np.array([1,2,3,5,6,6,7,7,9,8,6,5,12])
np.unique(a)

array([ 1,  2,  3,  5,  6,  7,  8,  9, 12])

In [136]:
a[a%2 == 0]
print(a) 

[ 1  2  3  5  6  6  7  7  9  8  6  5 12]


In [137]:
a[a != 5]
print(a) 

[ 1  2  3  5  6  6  7  7  9  8  6  5 12]


# Broadcasting practice :- 

In [4]:
#create arrays of different shapes,
#perform operations using braodcasting
# add a row vector to each row of matrix 
#1D
import numpy as np

array1 = np.array([1,2,3])
array2 = np.array([4,5,6]) 

addition = array1 + array2

print(addition)

vector = np.array([10,20,30])

result = addition + vector

print("result")

[5 7 9]
[15 27 39]


In [7]:
#2D
array3 = np.array([[1,2,3],[4,5,6]])

vector = np.array([[10,20,30],[40,50,60]])

result = array3 + vector

print(result)

[[11 22 33]
 [44 55 66]]


# Grade Analyzer :

In [21]:
# input student marks
# output 
#1.grades :a/b/c based on average 
#2.class average 
#3.top performer

marks = np.array([20,30,60,50,46,80,91])

#2.Average
average = np.mean(marks)
print(average)

#3. Top performer
topper = np.max(marks)
print(topper)

#1.grades
grades = np.where((marks>=35) & (marks<=45),"C", np.where((marks>45) & (marks<=60),"B", np.where((marks>60) & (marks<=85),"A", np.where((marks>90),"A+","Fail")))) 
print(grades)


53.857142857142854
91
['Fail' 'Fail' 'B' 'B' 'B' 'A' 'A+']


In [2]:
import numpy as np
arr = [2,3,4,5]
np.sum(arr)

np.int64(14)